apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: ec2confi-dev
spec:
  #ReadWriteOnce: Only one node can mount this volume as read-write
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi