apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}