apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ec2confi.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ec2confi-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        ports:
        - containerPort: {{ .Values.mysql.service.port }}
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
            claimName: mysql-pvc
