apiVersion: v1
kind: Service
metadata:
  name: ec2confi-service
  namespace: ec2confi-dev
spec:
  # NodePort allows external access to the service
  type: NodePort
  selector:
    app: ec2confi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # Fixed port to access from your host machine
      nodePort: 30080