name: CI - Spring Boot Docker

on:
  push:
    branches:
      - feature/register-system
      # after the ci is green=>>>>
      # - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      #1. check out source
      - name: Checkout code
        uses: actions/checkout@v4

      #2. Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven


      #3. Build Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      #4. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      #5. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-app:latest .

      # 6. Push image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-app:latest

